//
// Created by Fábio Sá on 23/12/2021.
//

#ifndef Y2S1_ALGORITMOSESTRUTURASDEDADOS_GRAPHS_H
#define Y2S1_ALGORITMOSESTRUTURASDEDADOS_GRAPHS_H


class Graphs {

};


#endif //Y2S1_ALGORITMOSESTRUTURASDEDADOS_GRAPHS_H
